module.exports = {
  OUTPUT_PATH: "./assets/images",
  MIN_FONTSIZE: 66,
  MAX_FONTSIZE: 114,
  BASE_FONTFAMILY: "RobotoSlab",
  SUB_FONTS: [
    "Regular",
    "Black",
    "Bold",
    "ExtraBold",
    "ExtraLight",
    "Light",
    "Medium",
  ],
  CANVAS_HEIGHT: 2430,
  CANVAS_WIDTH: 1770,
  PADDING: 120,
  LINESPACE: 40,
  WORDSPACE: 20,
};
